'use client';
import { useState } from 'react';
import { inspectJson, simulateHttp, parseNumbers, bubbleFrames, binarySteps, chunkText, wordSimilarity } from '../lib/lab-modules';

function Module({ number, title, intro, children }) { return <section className="interactive-module"><div className="module-heading"><p className="eyebrow">MODULE {number}</p><h2>{title}</h2><p>{intro}</p></div>{children}</section>; }
function JsonInspector() {
  const [input,setInput] = useState('{"name":"PindariCoders","topics":["coding","AI"],"open":true}');
  let result, error;
  try { result = inspectJson(input); } catch (issue) { error = issue.message; }
  return <Module number="01" title="make sense of JSON." intro="Paste a value. See its structure, format it, and catch invalid syntax. Your input stays in this browser."><div className="module-columns"><label>JSON input<textarea value={input} maxLength={20000} spellCheck={false} onChange={event=>setInput(event.target.value)} /></label><div className="module-output" aria-live="polite">{error ? <p className="module-error">{error}</p> : <><p className="eyebrow">{result.type.toUpperCase()}{result.count !== null && ` · ${result.count} TOP-LEVEL ENTRIES`}</p><pre>{result.formatted}</pre></>}</div></div><p className="module-hint">Try removing a quotation mark. JSON requires quoted keys and doesn’t allow trailing commas.</p></Module>;
}
function HttpSandbox() {
  const [method,setMethod]=useState('GET'),[path,setPath]=useState('/books'),[body,setBody]=useState('{"title":"A new idea"}');
  const result=simulateHttp(method,path,body);
  return <Module number="02" title="a request. a response." intro="An interactive HTTP simulation with sample routes. Nothing is sent to a server or saved."><div className="request-controls"><label>Method<select value={method} onChange={event=>setMethod(event.target.value)}>{['GET','POST','DELETE'].map(value=><option key={value}>{value}</option>)}</select></label><label>Route<select value={path} onChange={event=>setPath(event.target.value)}>{['/books','/books/1','/missing'].map(value=><option key={value}>{value}</option>)}</select></label></div>{method==='POST' && <label>Request body<textarea value={body} onChange={event=>setBody(event.target.value)} maxLength={2000} spellCheck={false} /></label>}<div className="http-response" aria-live="polite"><span className={`response-status ${result.status>=400?'is-error':''}`}>{result.status} {result.label}</span><pre>{result.body===null ? '(no response body)' : JSON.stringify(result.body,null,2)}</pre></div><p className="module-hint">Try POST /books with an empty title, then fix it. DELETE /books/1 shows why a 204 response has no body. Each scenario starts from the same sample data.</p></Module>;
}
function BubbleSort() {
  const [input,setInput]=useState('8, 3, 6, 1, 5'),[position,setPosition]=useState(0);
  let frames,error;
  try { frames=bubbleFrames(parseNumbers(input)); } catch(issue){error=issue.message;}
  const frame=frames?.[Math.min(position,frames.length-1)];
  return <Module number="01" title="one swap at a time." intro="Step through bubble sort. Compare neighboring values, swap when needed, and watch the largest values move right."><label>Numbers, separated by commas<input value={input} maxLength={100} onChange={event=>{setInput(event.target.value);setPosition(0);}} /></label>{error ? <p className="module-error" role="status">{error}</p> : <><div className="number-stage">{frame.items.map((value,index)=><span className={frame.active.includes(index)?'active-number':''} key={index}>{value}</span>)}</div><p className="step-explanation" aria-live="polite">{frame.text}</p><div className="module-actions"><button disabled={position===0} onClick={()=>setPosition(value=>value-1)}>← previous</button><span>{position+1} / {frames.length}</span><button disabled={position===frames.length-1} onClick={()=>setPosition(value=>value+1)}>next step →</button><button onClick={()=>setPosition(0)}>reset</button></div></>}<p className="module-hint">Use duplicates or negative numbers too. Bubble sort is useful for learning comparisons, but its worst-case work grows quadratically.</p></Module>;
}
function BinarySearch() {
  const [input,setInput]=useState('2, 5, 8, 12, 19, 24, 31'),[target,setTarget]=useState('19');
  let result,error;
  try { const values=parseNumbers(input); if(!/^-?\d+$/.test(target) || Math.abs(Number(target))>999) throw new Error('Enter a whole-number target from -999 to 999.'); result=binarySteps(values,Number(target)); } catch(issue){error=issue.message;}
  return <Module number="02" title="cut the search in half." intro="Binary search needs a sorted list. This module sorts your input first, then shows every decision."><div className="request-controls"><label>Numbers<input value={input} maxLength={100} onChange={event=>setInput(event.target.value)} /></label><label>Target<input value={target} maxLength={5} onChange={event=>setTarget(event.target.value)} /></label></div>{error ? <p className="module-error" role="status">{error}</p> : <><div className="number-stage">{result.items.map((value,index)=><span className={index===result.found?'active-number':''} key={index}>{value}</span>)}</div><div className="table-scroll"><table><caption>Search decisions (zero-based positions in the sorted list)</caption><thead><tr><th>Range</th><th>Middle</th><th>Value</th><th>Decision</th></tr></thead><tbody>{result.steps.map((step,index)=><tr key={index}><td>{step.low}–{step.high}</td><td>{step.mid}</td><td>{step.value}</td><td>{step.result}</td></tr>)}</tbody></table></div><p className="step-explanation" aria-live="polite">{result.found<0?'Not found. The search range is now empty.':`Found at position ${result.found} in the sorted list.`}</p></>}<p className="module-hint">Try a missing value. Each comparison discards half of the remaining search range.</p></Module>;
}
function TextChunker() {
  const [text,setText]=useState('A big idea gets easier when you break it into smaller pieces. Text chunking does something similar for a document. Each chunk carries part of the original text. Overlap repeats a little context so a thought near a boundary is less likely to be lost. Change the size and overlap to see the trade-off.'),[size,setSize]=useState(100),[overlap,setOverlap]=useState(20);
  const chunks=chunkText(text,size,overlap);
  return <Module number="01" title="big text. smaller pieces." intro="Explore character-based chunking, a preprocessing technique used in document retrieval. This isn’t a tokenizer and doesn’t call an AI model."><label>Your text<textarea value={text} maxLength={4000} onChange={event=>setText(event.target.value)} /></label><div className="request-controls"><label>Chunk size: {size} characters<input type="range" min="40" max="400" step="10" value={size} onChange={event=>{const next=Number(event.target.value);setSize(next);setOverlap(value=>Math.min(value,next-1));}} /></label><label>Overlap: {overlap} characters<input type="range" min="0" max={size-1} value={overlap} onChange={event=>setOverlap(Number(event.target.value))} /></label></div><p aria-live="polite">{chunks.length} chunks · {Array.from(text).length} characters</p><div className="chunk-list">{chunks.map((chunk,index)=><article key={index}><p className="eyebrow">CHUNK {index+1} / POSITIONS {chunk.start}–{chunk.end-1}</p><p>{chunk.text}</p></article>)}</div>{!chunks.length && <p className="module-hint">Type some text to create your first chunk.</p>}</Module>;
}
function Similarity() {
  const [first,setFirst]=useState('learn coding build small projects'),[second,setSecond]=useState('build coding projects together');
  const result=wordSimilarity(first,second);
  return <Module number="02" title="how much do these words overlap?" intro="Turn word counts into vectors and compare their direction with cosine similarity. This measures shared vocabulary, not meaning or AI embeddings."><div className="module-columns"><label>Text A<textarea value={first} maxLength={1000} onChange={event=>setFirst(event.target.value)} /></label><label>Text B<textarea value={second} maxLength={1000} onChange={event=>setSecond(event.target.value)} /></label></div><div className="similarity-result" aria-live="polite"><strong>{result.empty?'—':result.score.toFixed(3)}</strong><span>{result.empty?'Enter at least one word in each text.':'cosine similarity · 0 = no shared words, 1 = aligned word counts'}</span></div><div className="table-scroll"><table><caption>Word-count vectors (case-insensitive; punctuation removed)</caption><thead><tr><th>Word</th><th>Text A</th><th>Text B</th></tr></thead><tbody>{result.rows.map(row=><tr key={row.word}><td>{row.word}</td><td>{row.a}</td><td>{row.b}</td></tr>)}</tbody></table></div><p className="module-hint">Try “happy” and “joyful.” Related meanings can score zero here because the words differ. That’s a limitation of word counts.</p></Module>;
}
export default function DomainModules({domain}) { return <div className="domain-modules">{domain==='backend'?<><JsonInspector/><HttpSandbox/></>:domain==='algorithms'?<><BubbleSort/><BinarySearch/></>:<><TextChunker/><Similarity/></>}</div>; }
