'use client';
import { useEffect } from 'react';
import { mountPlaygrounds } from '../lib/playgrounds.js';
import RoadmapSection from './roadmap-section';
export default function Home() {
  useEffect(mountPlaygrounds, []);
  return (<><main>
  <section className="hero wrap" aria-labelledby="hero-title">
    <div className="hero-copy">
      <p className="eyebrow"><span className="tiny-cross" aria-hidden="true">+</span> AN INTERNET CORNER, MADE WITH CURIOSITY</p>
      <h1 id="hero-title">less scrolling.<br />more <span className="underline">making.</span></h1>
      <p className="hero-description">Small experiments. Useful little tools. Things learned along the way. A place to poke around, break things, and find your next “oh, that’s how.”</p>
      <a className="button primary" href="#experiments">find something to play with <span aria-hidden="true">↘</span></a>
      <div className="hero-footnote"><span className="ascii" aria-hidden="true">&#123; : ) &#125;</span><span>no sign-ups. just a curious mind.</span></div>
    </div>
    <div className="hero-play" id="playground">
      <span className="margin-note">go on, move things around ↴</span>
      <section className="lab-window" aria-labelledby="flex-title">
        <div className="window-bar"><span className="window-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>little-layout-lab.css</span><span aria-hidden="true">⌘</span></div>
        <div className="lab-top"><div><p className="eyebrow">EXPERIMENT 001</p><h2 id="flex-title">a little flex.</h2></div><span className="tag">interactive</span></div>
        <div className="flex-canvas" id="flex-canvas" aria-label="Live Flexbox preview"><span className="canvas-label">your canvas</span><div className="flex-items" id="flex-items"><div>01</div><div>02</div><div>03</div></div></div>
        <div className="lab-controls"><label htmlFor="justify">justify-content<select id="justify" defaultValue="center"><option value="flex-start">flex-start</option><option value="center" >center</option><option value="flex-end">flex-end</option><option value="space-between">space-between</option><option value="space-around">space-around</option><option value="space-evenly">space-evenly</option></select></label><label htmlFor="gap">gap <output id="gap-value" htmlFor="gap">12px</output><input id="gap" type="range" min="0" max="32" defaultValue="12" /></label></div>
        <div className="code-footer"><code id="flex-code">display: flex; gap: 12px;</code><button id="copy-css" className="text-button">copy CSS <span aria-hidden="true">↗</span></button></div>
        <p className="sr-only" id="copy-status" role="status"></p>
      </section>
      <span className="small-sticker">built to be<br /><strong>messed with.</strong></span>
    </div>
  </section>
  <div className="ticker" aria-label="Make something, learn something, repeat"><div className="wrap"><span>MAKE SOMETHING</span><b aria-hidden="true">✳</b><span>LEARN SOMETHING</span><b aria-hidden="true">✳</b><span>GET A LITTLE STUCK</span><b aria-hidden="true">✳</b><span>FIGURE IT OUT</span><b aria-hidden="true">✳</b><span>REPEAT</span></div></div>
  <section className="section wrap" id="experiments" aria-labelledby="experiments-title">
    <div className="section-head"><div><p className="eyebrow">01 / THE LAB</p><h2 id="experiments-title">small things. big rabbit holes.</h2></div><p>Made for the fun of figuring it out.<br />Pick one. See where it takes you.</p></div>
    <div className="experiment-grid">
      <a className="experiment-card" href="#playground"><div className="card-visual flex-visual" aria-hidden="true"><div className="mini-blocks"><span>01</span><span>02</span><span>03</span></div><span className="visual-caption">← a little room to move →</span><span className="card-index">001</span></div><div className="card-meta"><span className="eyebrow">CSS · PLAYGROUND</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>a little flex.</h3><p>Move three boxes. Make Flexbox click.</p></a>
      <button className="experiment-card" data-open="type-dialog"><div className="card-visual type-visual" aria-hidden="true"><span className="type-sample">Aa<span>*</span></span><span className="visual-caption">same words, different feeling.</span><span className="card-index">002</span></div><div className="card-meta"><span className="eyebrow">TYPE · EXPERIMENT</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>type something.</h3><p>A tiny playground for words with personality.</p></button>
      <button className="experiment-card" data-open="color-dialog"><div className="card-visual color-visual" aria-hidden="true"><div className="swatches"><span></span><span></span><span></span><span></span></div><span className="visual-caption">find a pair that gets along.</span><span className="card-index">003</span></div><div className="card-meta"><span className="eyebrow">COLOR · TOOL</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>good together.</h3><p>Play with color. Check if your words are readable.</p></button>
    </div>
  </section>
  <RoadmapSection /><section className="notes-section" id="notes" aria-labelledby="notes-title"><div className="wrap section">
    <div className="section-head"><div><p className="eyebrow">02 / FIELD NOTES</p><h2 id="notes-title">a few things that clicked.</h2></div><p>Short reads for your next coffee break.</p></div>
    <button className="note-row" data-open="note-flex"><span className="note-number">01</span><h3>Which way is the main axis, anyway?</h3><span className="note-topic">CSS</span><span className="note-time">2 min read</span><span aria-hidden="true">↗</span></button>
    <button className="note-row" data-open="note-type"><span className="note-number">02</span><h3>Your font size is only half the story.</h3><span className="note-topic">DESIGN</span><span className="note-time">2 min read</span><span aria-hidden="true">↗</span></button>
    <button className="note-row" data-open="note-build"><span className="note-number">03</span><h3>A small finished thing is a good place to start.</h3><span className="note-topic">BUILDING</span><span className="note-time">2 min read</span><span aria-hidden="true">↗</span></button>
  </div></section>
  <section className="about section wrap" id="about" aria-labelledby="about-title"><div><p className="eyebrow">03 / THE HUMAN BIT</p><h2 id="about-title">an old idea.<br />a fresh <span className="serif-word">start.</span></h2></div><div className="about-copy"><p>PindariCoders started as a university dream: a little place to build things and help others learn coding.</p><p>That idea sat on the shelf for a while. This is it finding its way back—one small experiment, one useful note, one finished thing at a time.</p><p>You don’t have to know everything to make something. There’s room here to figure it out.</p><a className="text-link" href="https://aboubakarisar.tech/" target="_blank" rel="noopener noreferrer">Abou Bakar Arisar, the person behind this <span aria-hidden="true">↗</span></a></div></section>
</main><dialog id="type-dialog" aria-labelledby="type-title"><button className="dialog-close" aria-label="Close typography playground">×</button><p className="eyebrow">EXPERIMENT 002</p><h2 id="type-title">type something.</h2><p>Change the spacing. Notice how the same words feel different.</p><label htmlFor="type-text">Your words<input id="type-text" maxLength="100" defaultValue="make a little mess." /></label><div className="type-controls"><label htmlFor="type-font">Typeface<select id="type-font"><option value="sans">Inter / sans serif</option><option value="serif">Georgia / serif</option><option value="mono">DM Mono / monospace</option></select></label><label htmlFor="type-size">Size <output id="type-size-value">48px</output><input type="range" id="type-size" min="20" max="80" defaultValue="48" /></label><label htmlFor="type-tracking">Letter spacing <output id="type-tracking-value">-2px</output><input type="range" id="type-tracking" min="-2" max="8" step="0.5" defaultValue="-2" /></label></div><div id="type-preview" className="type-preview">make a little mess.</div><code id="type-code">font-size: 48px; letter-spacing: -2px;</code></dialog>
<dialog id="color-dialog" aria-labelledby="color-title"><button className="dialog-close" aria-label="Close color playground">×</button><p className="eyebrow">EXPERIMENT 003</p><h2 id="color-title">good together.</h2><p>Try two colors. Contrast measures how easily the text stands out.</p><div className="color-controls"><label htmlFor="foreground">Text color<input id="foreground" type="color" defaultValue="#243427" /><output id="foreground-value">#243427</output></label><label htmlFor="background">Background<input id="background" type="color" defaultValue="#d9fa76" /><output id="background-value">#d9fa76</output></label></div><div className="contrast-preview" id="contrast-preview"><span>hello, good color.</span><p>Small words deserve to be readable, too.</p></div><div className="contrast-result" aria-live="polite"><strong id="contrast-ratio"></strong><span id="contrast-verdict"></span></div><p className="small-text">WCAG AA requires 4.5:1 for normal text and 3:1 for large text. This checks color contrast only.</p></dialog>
<dialog className="article-dialog" id="note-flex" aria-labelledby="note-flex-title"><button className="dialog-close" aria-label="Close article">×</button><p className="eyebrow">FIELD NOTE 01 / CSS</p><h2 id="note-flex-title">Which way is the main axis, anyway?</h2><p>Flexbox gets easier when you stop thinking of <code>justify-content</code> as “horizontal alignment.” It follows the main axis, and you get to choose that axis.</p><p>With <code>flex-direction: row</code>, items follow the inline direction—usually left to right in English. With <code>column</code>, they follow the block direction—usually top to bottom.</p><h3>Two properties, two jobs</h3><p><code>justify-content</code> distributes available space along the main axis. <code>align-items</code> aligns items along the cross axis. Change the direction and their visual roles change with it.</p><h3>Try it in the lab</h3><p>Choose <code>space-between</code> in “a little flex.” The outer boxes move to the edges; available space goes between them. Choose <code>center</code> and the group sits in the middle, keeping the gap you set.</p><p>If nothing moves, check whether the container has any extra space to distribute. Alignment can’t create spare room.</p><a href="https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox" target="_blank" rel="noopener noreferrer">Go deeper on MDN ↗</a></dialog>
<dialog className="article-dialog" id="note-type" aria-labelledby="note-type-title"><button className="dialog-close" aria-label="Close article">×</button><p className="eyebrow">FIELD NOTE 02 / DESIGN</p><h2 id="note-type-title">Your font size is only half the story.</h2><p>A heading can be huge and still feel awkward. The space inside and around the words does just as much work as the size.</p><h3>Start with the words</h3><p>Use your actual headline when choosing a typeface. A beautiful “Aa” sample doesn’t tell you how a long sentence will wrap on a phone.</p><h3>Give each size its own rhythm</h3><p>Large headings can often use tighter letter spacing. Small text usually needs more breathing room. Treat both as starting points to inspect, not rules to apply blindly.</p><p>Line height controls the distance between lines. Try roughly 1.5 for paragraphs, then check the actual font. Headings can be tighter, but tall letters and descenders must never collide.</p><h3>One small experiment</h3><p>Open “type something.” Keep the words the same and change only the typeface. Next, change the letter spacing. Look for the point where a little character becomes hard to read.</p><p>Then test your page on a narrow screen and with enlarged text. Good typography still works when the reader changes the conditions.</p></dialog>
<dialog className="article-dialog" id="note-build" aria-labelledby="note-build-title"><button className="dialog-close" aria-label="Close article">×</button><p className="eyebrow">FIELD NOTE 03 / BUILDING</p><h2 id="note-build-title">A small finished thing is a good place to start.</h2><p>You can make a useful project before you feel ready to build a platform. Pick one person, one problem, and one thing the page should let them do.</p><h3>Make the finish line visible</h3><p>“Build a developer toolkit” has no obvious end. “Let someone pick two colors and check their contrast” has a clear result you can test.</p><p>Write that result down before opening your editor. When the project begins growing extra features, come back to it.</p><h3>Let someone use it</h3><p>Share a working link with a friend. Give them a task, then watch without explaining the interface. Where they hesitate is useful feedback.</p><h3>Keep the lesson</h3><p>Write down one thing that broke and how you fixed it. That’s already the beginning of a helpful post. It doesn’t need to be a complete course.</p><p>Finishing something small gives you something real to improve—and a much better starting point for the next idea.</p></dialog>
</>);
}
