'use client';
import { useEffect } from 'react';
import { mountPlaygrounds } from '../lib/playgrounds';
export default function Lab() { useEffect(mountPlaygrounds, []); return <><main><section className="hero wrap" aria-labelledby="hero-title">
    <div className="hero-copy">
      <p className="eyebrow"><span className="tiny-cross" aria-hidden="true">+</span> THE LAB / LEARN BY DOING</p>
      <h1 id="hero-title">a little room<br />to <span className="underline">play.</span></h1>
      <p className="hero-description">Small experiments. Useful little tools. Things learned along the way. A place to poke around, break things, and find your next “oh, that’s how.”</p>
      <a className="button primary" href="#experiments">find something to play with <span aria-hidden="true">↘</span></a>
      <div className="hero-footnote"><span className="ascii" aria-hidden="true">&#123; : ) &#125;</span><span>no sign-ups. just a curious mind.</span></div>
    </div>
    <div className="hero-play" id="playground">
      <span className="margin-note">go on, move things around ↴</span>
      <section className="lab-window" aria-labelledby="flex-title">
        <div className="window-bar"><span className="window-dots" aria-hidden="true"><i></i><i></i><i></i></span><span>little-layout-lab.css</span><span aria-hidden="true">⌘</span></div>
        <div className="lab-top"><div><p className="eyebrow">EXPERIMENT 001</p><h2 id="flex-title">a little flex.</h2></div><span className="tag">interactive</span></div>
        <div className="flex-canvas" id="flex-canvas" aria-label="Live Flexbox preview"><span className="canvas-label">your canvas</span><div className="flex-items" id="flex-items"><div>01</div><div>02</div><div>03</div></div></div>
        <div className="lab-controls"><label htmlFor="justify">justify-content<select id="justify" defaultValue="center"><option value="flex-start">flex-start</option><option value="center" >center</option><option value="flex-end">flex-end</option><option value="space-between">space-between</option><option value="space-around">space-around</option><option value="space-evenly">space-evenly</option></select></label><label htmlFor="gap">gap <output id="gap-value" htmlFor="gap">12px</output><input id="gap" type="range" min="0" max="32" defaultValue="12" /></label></div>
        <div className="code-footer"><code id="flex-code">display: flex; gap: 12px;</code><button id="copy-css" className="text-button">copy CSS <span aria-hidden="true">↗</span></button></div>
        <p className="sr-only" id="copy-status" role="status"></p>
      </section>
      <span className="small-sticker">built to be<br /><strong>messed with.</strong></span>
    </div>
  </section>
  <div className="ticker" aria-label="Make something, learn something, repeat"><div className="wrap"><span>MAKE SOMETHING</span><b aria-hidden="true">✳</b><span>LEARN SOMETHING</span><b aria-hidden="true">✳</b><span>GET A LITTLE STUCK</span><b aria-hidden="true">✳</b><span>FIGURE IT OUT</span><b aria-hidden="true">✳</b><span>REPEAT</span></div></div>
  <section className="section wrap" id="experiments" aria-labelledby="experiments-title">
    <div className="section-head"><div><p className="eyebrow">01 / THE LAB</p><h2 id="experiments-title">small things. big rabbit holes.</h2></div><p>Made for the fun of figuring it out.<br />Pick one. See where it takes you.</p></div>
    <div className="experiment-grid">
      <a className="experiment-card" href="#playground"><div className="card-visual flex-visual" aria-hidden="true"><div className="mini-blocks"><span>01</span><span>02</span><span>03</span></div><span className="visual-caption">← a little room to move →</span><span className="card-index">001</span></div><div className="card-meta"><span className="eyebrow">CSS · PLAYGROUND</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>a little flex.</h3><p>Move three boxes. Make Flexbox click.</p></a>
      <button className="experiment-card" data-open="type-dialog"><div className="card-visual type-visual" aria-hidden="true"><span className="type-sample">Aa<span>*</span></span><span className="visual-caption">same words, different feeling.</span><span className="card-index">002</span></div><div className="card-meta"><span className="eyebrow">TYPE · EXPERIMENT</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>type something.</h3><p>A tiny playground for words with personality.</p></button>
      <button className="experiment-card" data-open="color-dialog"><div className="card-visual color-visual" aria-hidden="true"><div className="swatches"><span></span><span></span><span></span><span></span></div><span className="visual-caption">find a pair that gets along.</span><span className="card-index">003</span></div><div className="card-meta"><span className="eyebrow">COLOR · TOOL</span><span className="circle-arrow" aria-hidden="true">↗</span></div><h3>good together.</h3><p>Play with color. Check if your words are readable.</p></button>
    </div>
  </section>
</main><dialog id="type-dialog" aria-labelledby="type-title"><button className="dialog-close" aria-label="Close typography playground">×</button><p className="eyebrow">EXPERIMENT 002</p><h2 id="type-title">type something.</h2><p>Change the spacing. Notice how the same words feel different.</p><label htmlFor="type-text">Your words<input id="type-text" maxLength="100" defaultValue="make a little mess." /></label><div className="type-controls"><label htmlFor="type-font">Typeface<select id="type-font"><option value="sans">Inter / sans serif</option><option value="serif">Georgia / serif</option><option value="mono">DM Mono / monospace</option></select></label><label htmlFor="type-size">Size <output id="type-size-value">48px</output><input type="range" id="type-size" min="20" max="80" defaultValue="48" /></label><label htmlFor="type-tracking">Letter spacing <output id="type-tracking-value">-2px</output><input type="range" id="type-tracking" min="-2" max="8" step="0.5" defaultValue="-2" /></label></div><div id="type-preview" className="type-preview">make a little mess.</div><code id="type-code">font-size: 48px; letter-spacing: -2px;</code></dialog>
<dialog id="color-dialog" aria-labelledby="color-title"><button className="dialog-close" aria-label="Close color playground">×</button><p className="eyebrow">EXPERIMENT 003</p><h2 id="color-title">good together.</h2><p>Try two colors. Contrast measures how easily the text stands out.</p><div className="color-controls"><label htmlFor="foreground">Text color<input id="foreground" type="color" defaultValue="#243427" /><output id="foreground-value">#243427</output></label><label htmlFor="background">Background<input id="background" type="color" defaultValue="#d9fa76" /><output id="background-value">#d9fa76</output></label></div><div className="contrast-preview" id="contrast-preview"><span>hello, good color.</span><p>Small words deserve to be readable, too.</p></div><div className="contrast-result" aria-live="polite"><strong id="contrast-ratio"></strong><span id="contrast-verdict"></span></div><p className="small-text">WCAG AA requires 4.5:1 for normal text and 3:1 for large text. This checks color contrast only.</p></dialog>
</>; }
