import Link from 'next/link';
import { founders } from '../../lib/founders';
export const metadata = { title: 'Our story', description: 'The story of Abou Bakar and Muhammad Abdullah: two friends returning to an idea for helping people learn coding and explore technology.' };
export default function StoryPage() {
return <main className="wrap section story-page"><div className="story-intro"><div className="page-heading"><p className="eyebrow">THE HUMAN BIT</p><h1>the page went quiet.<br />the idea <span className="serif-word">didn’t.</span></h1></div><div className="story-opening"><p>Some ideas don’t disappear when you stop working on them. They wait.</p><p>For us, that idea was PindariCoders: a place where someone curious about coding could find a little direction, try things out, and feel welcome before they felt experienced.</p><p>We started it. We paused it. And now we’re giving it another beginning.</p></div></div>
<section className="founder-grid" aria-label="Abou Bakar and Muhammad Abdullah">{founders.map(person=><article className="founder-card" key={person.name}><div className="founder-photo"><img src={person.photo} alt={person.alt} width="1103" height="1426" /></div><div className="founder-info"><h2>{person.name}</h2>{person.portfolio && <a className="circle-arrow" aria-label={`${person.name}’s portfolio`} href={person.portfolio} target="_blank" rel="noopener noreferrer">↗</a>}</div></article>)}</section>
<div className="story-chapters"><section className="story-chapter"><div><p className="eyebrow">01 / THE FIRST SPARK</p><h2>what if we made<br />a place for <span className="serif-word">this?</span></h2></div><div><p>We’re Abou Bakar and Muhammad Abdullah. Back in university, we wanted to create something around the things we were interested in: coding, technology, and helping other people learn.</p><p>The idea wasn’t complicated. Share what’s useful. Make learning feel approachable. Give people a way to follow what’s happening in tech without losing sight of the basics.</p><p>So we gave it a name, PindariCoders, and started a Facebook page and a YouTube channel. That was our first version: a small space on platforms people already used, with a bigger hope behind it.</p></div></section>
<section className="story-chapter"><div><p className="eyebrow">02 / THE QUIET PART</p><h2>starting was one thing.<br /><span className="serif-word">continuing</span> was another.</h2></div><div><p>We couldn’t keep it going. There wasn’t a finished platform or a steady stream of content waiting on the other side. The pages went quiet, and the idea stayed unfinished.</p><p>For Abou Bakar, a lack of confidence and the rapid rise of AI made it harder to continue. When technology moves that quickly, it’s easy to question where your own work fits.</p><p>That’s part of this story too. We don’t want to present a perfect beginning when the real one included hesitation and a pause. An unfinished idea can still matter to the people who started it.</p></div></section>
<blockquote className="story-pullquote">“You don’t have to know everything<br />to help someone take <em>one step.</em>”<span>THE IDEA WE’RE BUILDING AROUND</span></blockquote>
<section className="story-chapter"><div><p className="eyebrow">03 / A DIFFERENT WAY BACK</p><h2>less waiting to be ready.<br />more <span className="serif-word">making.</span></h2></div><div><p>This version starts smaller and makes room for doing. A learning path can help you choose what comes next. A lab can turn a confusing concept into something you can change and observe. A useful resource can save you an afternoon of searching.</p><p>And technology keeps moving, so there’s a place for that too: a feed of AI stories and conversations, with links back to the people publishing and discussing them.</p><p>These are different ways into the same space. You might arrive because you want to understand an API response. You might stay because an algorithm finally makes sense when you watch it step through a list.</p></div></section>
<section className="story-chapter"><div><p className="eyebrow">04 / THE SPACE WE WANT TO MAKE</p><h2>curiosity belongs here.<br />so do <span className="serif-word">you.</span></h2></div><div><p>We want PindariCoders to be useful before it tries to be impressive. Clear explanations. Small things you can play with. Honest limits on what a tool does. Resources with a reason to be on the shelf.</p><p>You don’t need a perfect plan to use any of it. Pick a domain. Change an input. Follow a link. Build a small thing, get stuck, and come back with a better question.</p><p>We’re still shaping this place. But the reason for making it hasn’t changed: helping others learn coding, explore technology, and see what they can make for themselves.</p><p>That was the idea then. This is us coming back to it.</p><Link className="button primary" href="/lab/">find your first experiment ↗</Link></div></section></div>
<div className="story-socials"><span>where the idea first found a home</span><a href="https://web.facebook.com/100091890139657/" target="_blank" rel="noopener noreferrer">facebook ↗</a><a href="https://www.youtube.com/channel/UCjcPe7QIgs5D9UVULDuXGWQ" target="_blank" rel="noopener noreferrer">youtube ↗</a></div></main>;
}
